edenia/Eden

.github/workflows/push-dev-environment.yaml

In this PR the corrections for the action push-dev-environment are made, additionally the deployment of Kubernetes in development is added.

final changes to make the PR

---

contracts/eden/tests/include/tester-base.hpp
contracts/eden/tests/test-eden.cpp

- Fix `budget distribution` unit test
- Correct indentations

fix(contract): budget distribution

---

.github/workflows/push-dev-environment.yaml
.github/workflows/push-pdn-environment.yaml
docker/eden-box.Dockerfile
docker/eden-webapp.Dockerfile

* Fix the error for build process for webapp image.
* Fix the warning in all steps for the actions to build and deploy in the dev a prod envioroment.

devops(webapp-box): Fix actions deploy dev and pdn envioroment

---

packages/webapp/src/_app/ui/footer.tsx
packages/webapp/src/home/components/learn-more-cta.tsx
packages/webapp/src/home/components/welcome-text.tsx
packages/webapp/src/video-conferencing/terms-of-use.tsx

- Remove Eden Peace Treaty link

feat(webapp): remove peace treaty link

---

packages/webapp/src/_app/ui/footer.tsx
packages/webapp/src/video-conferencing/terms-of-use.tsx

- Update footer text
- Remove unused imported component

refactor(webapp): clean code

---

packages/webapp/src/_app/ui/footer.tsx

- reduce spacing in the footer components

refactor(webapp): adjust spacing in the footer

---

contracts/eden/src/eden-micro-chain.cpp

- Add `removemember` action event to the microchain
- Autoformat the `eden-micro-chain.cpp` file according to the rules set

fix(contracts): add removemember event to the microchain

---

.github/workflows/push-dev-environment.yaml
.github/workflows/push-pdn-environment.yaml

fix(webapp): modify the value for max fetch rows per sec in .env webapp

fix(webapp): modify the value for max fetch rows per sec in .env webapp

---

packages/webapp/src/_app/ui/footer.tsx
packages/webapp/src/_app/ui/video-form.tsx
packages/webapp/src/pages/election/round-video-upload.tsx

Validation applied when the user wants to upload a file and the choice has not finished

feat(webapp): applied validation on upload video button

---

packages/webapp/src/_app/styles/nprogress.tailwind.css
packages/webapp/src/_app/ui/video-form.tsx
packages/webapp/src/elections/components/ongoing-election-components/video-upload-button.tsx
packages/webapp/src/pages/election/round-video-upload.tsx

Added message on upload video button

---

.github/workflows/push-pdn-environment.yaml

fix(webapp): Increase rate limiter pdn

fix(webapp): Increase rate limiter pdn

---

packages/webapp/src/elections/components/registration-election-components/participation-card.tsx

feat(components): changed date format

---

packages/webapp/src/elections/components/registration-election-components/election-schedule-segment.tsx
packages/webapp/src/elections/components/registration-election-components/participation-card.tsx
packages/webapp/src/elections/utils.ts

feat(components): improved format date

---

packages/webapp/package.json
packages/webapp/src/_app/eos/ual/EdenUALProvider.tsx
packages/webapp/src/_app/eos/ual/config.ts
yarn.lock

feat(webapp): removed scatter wallet

---

packages/webapp/package.json
packages/webapp/src/_app/eos/ual/EdenUALProvider.tsx
packages/webapp/src/_app/eos/ual/config.ts
yarn.lock

Revert "feat(webapp): removed scatter wallet"

---

.github/workflows/push-pdn-environment.yaml

fix(webapp):disable scatter wallet

fix(webapp):disable scatter wallet

---

packages/webapp/src/elections/components/registration-election-components/election-schedule-segment.tsx
packages/webapp/src/elections/components/registration-election-components/participation-card.tsx
packages/webapp/src/elections/utils.ts

Revert "feat(components): changed date format UTC"

Revert "feat(components): changed date format UTC"

---

.github/workflows/push-pdn-environment.yaml

* fix(devops): update rpc endpoint url

Change rpc endpoint url pdn (#102)

---

.github/workflows/push-pdn-environment.yaml
docker/eden-box.Dockerfile
docker/eden-webapp.Dockerfile

fix(env) update AA endpoint pdn

fix(env) update AA endpoint pdn

---

packages/webapp/src/elections/components/ongoing-election-components/ongoing-round/round-info/consensometer.tsx

- Fix typo in message `Leader must vote for themself`

fix(webapp): typo

---

contracts/eden/src/actions/elect.cpp
contracts/eden/tests/test-eden.cpp

- Disable the ability to issue `SBT` during an election.

chore(contract): comment the logic to issue sbt from the smart contract

---

contracts/eden/src/actions/elect.cpp
contracts/eden/tests/test-eden.cpp
packages/webapp/src/elections/components/ongoing-election-components/ongoing-round/round-info/consensometer.tsx

Production release
